#############################################################################
# Makefile for building: AndroigBijia.app/Contents/MacOS/AndroigBijia
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  AndroigBijia.pro
# Template: app
# Command: /Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile AndroigBijia.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang -I. -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib
QMAKE         = /Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AndroigBijia1.0.0
DISTDIR = /Users/tobyyi/Downloads/AndroigBijia/.tmp/AndroigBijia1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = ../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/lex.prf \
		AndroigBijia.pro  main.cpp
QMAKE_TARGET  = AndroigBijia
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = AndroigBijia.app/Contents/MacOS/AndroigBijia

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d AndroigBijia.app/Contents/MacOS/ || mkdir -p AndroigBijia.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AndroigBijia.pro ../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/lex.prf \
		AndroigBijia.pro \
		qml.qrc \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile AndroigBijia.pro
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qml_debug.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/declarative_debug.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resources.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/moc.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/uic.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/lex.prf:
AndroigBijia.pro:
qml.qrc:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile AndroigBijia.pro

qmake_all: FORCE

AndroigBijia.app/Contents/PkgInfo: 
	@test -d AndroigBijia.app/Contents || mkdir -p AndroigBijia.app/Contents
	@$(DEL_FILE) AndroigBijia.app/Contents/PkgInfo
	@echo "APPL????" >AndroigBijia.app/Contents/PkgInfo
AndroigBijia.app/Contents/Resources/empty.lproj: 
	@test -d AndroigBijia.app/Contents/Resources || mkdir -p AndroigBijia.app/Contents/Resources
	@touch AndroigBijia.app/Contents/Resources/empty.lproj
	
AndroigBijia.app/Contents/Info.plist: 
	@test -d AndroigBijia.app/Contents || mkdir -p AndroigBijia.app/Contents
	@$(DEL_FILE) AndroigBijia.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.dtuandui.myfirst.AndroigBijia,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,AndroigBijia,g" -e "s,@TYPEINFO@,????,g" ../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >AndroigBijia.app/Contents/Info.plist

all: Makefile \
		AndroigBijia.app/Contents/PkgInfo \
		AndroigBijia.app/Contents/Resources/empty.lproj \
		AndroigBijia.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r AndroigBijia.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		MainForm.ui.qml \
		main2.qml \
		DragAndDropTextItem.qml \
		dragdrop.js \
		mainview.qml \
		drop.json \
		DragAndDropItem.qml \
		main.qml
	/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp ../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlApplicationEngine \
		../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlapplicationengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/AndroigBijia/bin || mkdir -p $(INSTALL_ROOT)/opt/AndroigBijia/bin
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/AndroigBijia/bin/AndroigBijia.app"
	
	-$(INSTALL_DIR) "AndroigBijia.app" "$(INSTALL_ROOT)/opt/AndroigBijia/bin/AndroigBijia.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/AndroigBijia/bin/AndroigBijia.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/AndroigBijia/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

